### PR TITLE
Change license

### PR DESCRIPTION
**Pull request by Shemnei**
Change license to a dual license of MIT and Apache-2.0.

For the change process, the template from <https://github.com/emberian/relicense-assistant/blob/master/single-issue-template.md> was used.

### CODE REVIEW

**Comment by Shemnei** [comment]
@michidk if you approve of changing the license, please comment with something along the lines of `I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.` to finalize this change.

**Comment by Shemnei** [comment]
bors try

**Comment by michidk** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Pull request merged**
